version: "3"
services:
  manager:
    build: ./manager
    container_name: manager
    restart: always
    volumes:
      - ./manager:/usr/src/app
    command: "npm run dev"

  users:
    build: ./users
    container_name: users
    restart: always
    volumes:
      - ./users:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c 'npm install; npm start'
    environment:
      DATABASE_URL: mongodb://mongo/users
    depends_on:
      - mongo
    
  mongo:
    container_name: mongo
    image: mongo

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - users