version: "3"
services:
  client:
    build: ./client
    container_name: client
    volumes:
      - ./client:/usr/src/app
    ports:
      - "3000:3000"

  users:
    build: ./users
    container_name: users
    restart: always
    volumes:
      - ./users:/usr/src/app
    ports:
      - "3001:3000"
    working_dir: /usr/src/app
    command: sh -c 'npm install; npm start'
    environment:
      DATABASE_HOST: mongo
    depends_on:
      - mongo
    
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./client/build:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - users