export const STARTING_USER_UPDATE = 'STARTING_USER_UPDATE'
export const USER_UPDATE_SUCCESSFUL = 'USER_UPDATE_SUCCESSFUL'
export const USER_UPDATE_FAILED = 'USER_UPDATE_FAILED'
export const CLEAR_USER_UPDATE_ERRORS = 'CLEAR_USER_UPDATE_ERRORS'
