version: "3"
services:
  users:
    build: .
    container_name: users
    restart: always
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    command: sh -c 'npm install; npm start'
    environment:
      DATABASE_HOST: mongo
    
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"